# Generated by Django 6.0.1 on 2026-08-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0072_audittrail'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemaster',
            name='education_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='government_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='highest_hindi_exam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='hindi_knowledge',
            field=models.CharField(blank=True, choices=[('Proficient', 'Proficient'), ('Working Knowledge', 'Working Knowledge'), ('Not at All', 'Not at All')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='hindi_subject_graduation',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='hindi_subject_matric',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='matric_medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='official_work_in_hindi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='place_of_posting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='retirement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
