# Generated by Django 6.0.1 on 2026-08-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0072_audittrail'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='education_qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hindi_in_graduation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hindi_in_matric',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='matric_medium',
            field=models.CharField(blank=True, choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Telugu', 'Telugu'), ('Tamil', 'Tamil'), ('Kannada', 'Kannada'), ('Malayalam', 'Malayalam'), ('Marathi', 'Marathi'), ('Gujarati', 'Gujarati'), ('Punjabi', 'Punjabi'), ('Bengali', 'Bengali'), ('Odia', 'Odia'), ('Urdu', 'Urdu'), ('Other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='mother_tongue',
            field=models.CharField(blank=True, choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Telugu', 'Telugu'), ('Tamil', 'Tamil'), ('Kannada', 'Kannada'), ('Malayalam', 'Malayalam'), ('Marathi', 'Marathi'), ('Gujarati', 'Gujarati'), ('Punjabi', 'Punjabi'), ('Bengali', 'Bengali'), ('Odia', 'Odia'), ('Urdu', 'Urdu'), ('Assamese', 'Assamese'), ('Other', 'Other')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='official_work_in_hindi',
            field=models.CharField(blank=True, choices=[('Always', 'Always'), ('Mostly', 'Mostly'), ('Sometimes', 'Sometimes'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='highest_exam',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Prabodh', 'Prabodh'), ('Praveen', 'Praveen'), ('Pragya', 'Pragya'), ('Parangat', 'Parangat')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hindiproficiency',
            field=models.CharField(blank=True, choices=[('Proficient', 'Proficient'), ('Working Knowledge', 'Working Knowledge'), ('Not at All', 'Not at All')], max_length=30, null=True),
        ),
    ]
