# Generated by Django 6.0.1 on 2026-08-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0073_employee_education_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='typing',
            field=models.CharField(blank=True, choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Both', 'Both')], max_length=30, null=True),
        ),
    ]
