# Generated by Django 6.0.1 on 2026-08-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0073_employeemaster_education_qualification_and_more'),
        ('website', '0074_alter_employee_typing'),
    ]

    operations = [
    ]
